### ISSUE TITLE
TODO: Small tweaks and enhancements

### ISSUE THREAD

**Issue by likethemammal** [cryptic-io/cryptic-chat#26]
- [x] Need more spacing in between tags in title.
- [x] Title needs more line-height
- [x] Disqus font color needs to have more contrast with background
- [x] Hover color for chat messages on front page need to switch to that light green thats in the mobile Hangouts app, **#def2d8**.
- [x] `page-header` class needs larger font-size and a `sub-header` class needs to be created for smaller headers.
- [x] Search spacing needs to be evened out and based on 11px multiples.
- [x] Search icon needs to be added to input field.
- [x] Title and alt text need to be added
- [x] Sort the members page alphabetically
- [x] Code snippet spacing needs to be adjusted by removing the margins on the `pre` tag.
- [x] Slightly reduce the padding of the inner container of the post page (maybe just on mobile).
- [x] Extend `max-width` of messages on the home page.
- [x] Optimize page use page speed test site.
